apiVersion: apps/v1
kind: Deployment
metadata:
  name: onehealth-historyandlifestyle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onehealth-historyandlifestyle
  template:
    metadata:
      labels:
        app: onehealth-historyandlifestyle
    spec:
      containers:
      - name: onehealth-historyandlifestyle
        image: yjb28/lifestyle:v11
        ports:
        - containerPort: 8080
      
---
apiVersion: v1
kind: Service
metadata:
  name: onehealth-historyandlifestyle
spec:
  selector:
    app: onehealth-historyandlifestyle
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30005
  type: LoadBalancer